server:
  port: 9003
spring:
  application:
    name: student-service
  config:
    import: "optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8888"
  cloud:
    config:
      fail-fast: false
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/sms_student?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
